<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5049" started-at="2014-04-21T07:25:33Z" finished-at="2014-04-21T07:25:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5049" started-at="2014-04-21T07:25:33Z" finished-at="2014-04-21T07:25:38Z">
      <class name="com.example.tests.TestContactCreation">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.example.tests.TestContactCreation@dd67cf]" name="setUp" is-config="true" duration-ms="14" started-at="2014-04-21T10:25:33Z" finished-at="2014-04-21T10:25:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="shouldCreateContactWithValidData()[pri:0, instance:com.example.tests.TestContactCreation@dd67cf]" name="shouldCreateContactWithValidData" duration-ms="5008" started-at="2014-04-21T10:25:33Z" finished-at="2014-04-21T10:25:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shouldCreateContactWithValidData -->
        <test-method status="FAIL" signature="tearDown()[pri:0, instance:com.example.tests.TestContactCreation@dd67cf]" name="tearDown" is-config="true" duration-ms="0" started-at="2014-04-21T10:25:38Z" finished-at="2014-04-21T10:25:38Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.example.fw.ProcessHelper.stopAppUnderTest(ProcessHelper.java:19)
	at com.example.fw.ApplicationManager.stop(ApplicationManager.java:21)
	at com.example.tests.TestBase.tearDown(TestBase.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.afterRun(TestRunner.java:1014)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.example.tests.TestContactCreation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
